function [DF] = interpolate_average_and_store(DF,o,phase,l,...
    frame_dur,norm_frame_dur)


% interpolate & average fluo response for a given individual 
[resu] = ...
    interpolate_and_average(...
    DF.indiv_stim{o,phase,l},...
    frame_dur,...
    norm_frame_dur);

% store the fluo response in new variable for pooling
fn = fieldnames(resu);

for i=1:length(fn)
    DF.(fn{i}){o,phase,l} = ...
        resu.(fn{i});
end
