function [Resp_odor_beg,Resp_odor_test,Resp_ctrl_odor_beg,Resp_ctrl_odor_test]=...
    significant_response(DF_Score_tp,indiv_id,Resp_ctrl_odor,...
    Resp_odor_beg,Resp_odor_test,Resp_ctrl_odor_beg,Resp_ctrl_odor_test)
        

% Test if there is a resp to odor (used to select the larvae)
% pool all 3 odors before training:
 y= [DF_Score_tp{1,1,indiv_id,1},...
    DF_Score_tp{2,1,indiv_id,1},...
    Resp_ctrl_odor{indiv_id,1}];

[~,Resp_odor_beg(indiv_id,1)] = ttest(y,...
    zeros(1,length(y)),'Tail','right');  

[~,Resp_ctrl_odor_beg(indiv_id,1)] = ttest(Resp_ctrl_odor{indiv_id,1},...
    zeros(size(Resp_ctrl_odor{indiv_id,1})),'Tail','right');  

% resp to odor after training:
y= [Resp_ctrl_odor{indiv_id,2},DF_Score_tp{1,2,indiv_id,1},...
    DF_Score_tp{2,2,indiv_id,1}];

[~,Resp_odor_test(indiv_id,1)] = ttest(y,...
    zeros(1,length(y)),'Tail','right');  

[~,Resp_ctrl_odor_test(indiv_id,1)] = ttest(Resp_ctrl_odor{indiv_id,2},...
    zeros(size(Resp_ctrl_odor{indiv_id,2})),'Tail','right');